name: "Dependabot Automerge"
on: pull_request_target
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: "Unit Tests"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Clean and Run Unit Tests
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 7.2
          arguments: clean assemble test
  automerge:
    name: "Automerge Dependabot PR"
    needs: [unit-tests]
    if: ${{github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target'}}
    runs-on: ubuntu-latest
    steps:
      - name: Rebase Dependabot PR
        uses: actions/github-script@v3
        with:
          script: |
            github.pulls.merge({
                owner: context.repo.owner,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number,
                merge_method: 'rebase'
            });